---

- name: Ensure directory for grafana exists
  become: yes
  file:
    path: /var/data/grafana
    owner: "472"
    state: directory

- name: Start grafana docker container
  become: yes
  docker_container:
    name: grafana_01
    image: grafana/grafana:7.0.0
    env:
      GF_SECURITY_ADMIN_USER: "{{ grafana.admin.user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana.admin.pass }}"
      GF_SECURITY_DISABLE_GRAVATAR: "true"
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "{{ mail.domain.sub }}.{{ mail.domain.apex }}:465"
      GF_SMTP_USER: "{{ mail.user.noreply.name }}"
      GF_SMTP_PASSWORD: "{{ mail.user.noreply.pass }}"
      GF_SMTP_FROM_ADDRESS: no_reply+grafana@rbn.is
      GF_SMTP_FROM_NAME: Grafana
    volumes:
    - /var/data/grafana:/var/lib/grafana
    published_ports:
    - 127.0.0.1:3000:3000
    log_driver: loki
    log_options:
      loki-url: https://{{ loki.user }}:{{ loki.pass }}@{{ loki.domain.sub }}.{{ loki.domain.apex }}/loki/api/v1/push
      loki-retries: "5"
      loki-batch-size: "400"
    user: root
    restart_policy: always
    state: started
  notify: Reload nginx

- name: Fire handlers
  meta: flush_handlers

- name: Create personal user
  community.grafana.grafana_user:
    grafana_url: https://{{ grafana.domain.sub }}.{{ grafana.domain.apex }}
    grafana_user: "{{ grafana.admin.user }}"
    grafana_password: "{{ grafana.admin.pass }}"
    name: "{{ grafana.user.name }}"
    email: "{{ grafana.user.mail }}"
    login: "{{ grafana.user.user }}"
    password: "{{ grafana.user.pass }}"
    is_admin: true
    state: present
