# Repository settings set via https://github.com/probot/settings

repository:
  has_issues: true
  has_wiki: false
  has_projects: false
  has_downloads: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true

labels:
  - name: update
    description: An update of some sort is needed
    color: 0366d6
  - name: security
    description: Update do prevent pwnage
    color: d73a4a
  - name: feature
    description: A new feature
    color: 008672
  - name: docs
    description: Documentation
    color: e3ed5e
