# Repository settings set via https://github.com/probot/settings

repository:
  has_issues: true
  has_wiki: false
  has_projects: false
  has_downloads: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true

labels:
  - name: update
    color: 0366d6
  - name: security
    color: d73a4a
  - name: feature
    color: 008672
