---

- name: Validate nginx config
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

- name: Reload nginx
  become: yes
  service:
    name: nginx
    state: reloaded

- name: Restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
