---

- name: Ensure locale en_US.UTF-8 locale is present
  become: yes
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Ensure the timezone is set to Europe/Berlin
  become: yes
  timezone:
    name: Europe/Berlin

- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: Upgrade all packages
  become: yes
  apt:
    upgrade: yes

- name: Autoremove not needed packages
  become: yes
  apt:
    autoremove: yes

- name: Install common packages
  become: yes
  apt:
    name:
    - unzip
    - tmux
    state: present
  check_mode: no

- name: Ensure pip3 is available
  become: yes
  apt:
    name:
    - python3
    - python3-pip
    state: present
  check_mode: no

- name: Install python-apt to check for installed packages
  pip:
    name: python-apt
  check_mode: no

- name: Make sure the group 'wheel' exists
  become: yes
  group:
    name: wheel
    state: present

- name: Allow the group 'wheel' to use sudo without password
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s
    mode: 0440

- name: Manage additional users
  become: yes
  user:
    name: "{{ item.name }}"
    shell: "/bin/bash"
    groups: wheel
    append: yes
  loop: "{{ users }}"

- name: Manage SSH Keys for additional Users
  become: yes
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
    exclusive: yes
  loop: "{{ users }}"
