name: Master deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.12 hcloud==1.9.1
    - name: Install ansible collections
      run: |
        ansible-galaxy collection install inwx.collection
        ansible-galaxy collection install community.grafana
    - name: Setup secrets
      run: |
        echo "${{ secrets.VAULT_PROD }}" > ~/.vault_prod
        mkdir ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Run ansible playbook
      run: ansible-playbook site.yml -i inventories/prod --vault-id prod@~/.vault_prod
